apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: todo-api-prod

labels:
- pairs:
    environment: prod
    tier: production
  includeSelectors: true

patches:
- path: patch-replicas.yaml
