apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-api-secret
  namespace: todo-api-prod
spec:
  encryptedData:
    API_KEY: AgAeHfDUgukoHyZqior2CFQi88m4IKn1R8dJ7ewg+0U/rFY9zgNgVM7yUgcbVLCrUL/O3A3vK+/Bflqi5DM32o0MjKstNOQYdz9i/RQ/mt5V6IYhfHmZde0LTEV1i0/1ioOCpfHqpwxv9nmIfIt5rF0fQqEkfJ5EUq6JWzVdOTw5EomZG+mQQ1g/ecYp5yBW+NnESDqr5qqofWGwKtBIZvF1FQBiWdvBy342ioJZgCZtNYEwToutB+1Cl9DylaLgV9tyggvmWg95ceHGTOvWC9/jUeUK3RfVJh7Ihg7q7G7gLcXZpuBwZOlGDpi2MdrGFrBRjUX97Cjj1B/Hx9bc6RAnfg8NqZyH1spCqde6462PoFp52IN+b+dMKz+nV1mjGgsopMzjAzWZlJRmsjxM9tqskGjyvFhUj0Di0tEgy2+qCJ00mgXJLKCwjX3uh0Bd6js0BtoecwERY1ZtSX/vKVtV85eWJBjqtf3oHtepqdRPPAB6tqxTURKnjWDGLIsXmKerFBom3YmXPZIYujky2TYggEUOdcqSBKaCDCcIiDUzWzhIBM84CwOU9F4w0hBEftcck6rqTDFTMOe2Q51x3gh34PdShE1hlFHuFomNEhLDI+4xvrJ+j5oeNzVBy124lBbDo9JXr71Yzo0/A0A2kkZgZGyUPyV1Q3vme0I+O6p+Dcg+HBmqypQlme7TZMj5GEQ1Li/f2JMsrb+b2HAQJBIZ
    DB_PASSWORD: AgB2ume43kDDNTUc60wLSQkmO9Fe0Xv67GqhRxuxf9Q6byVLIgnTH/rEBJIetGO4aYDAcHfamAmQO1WBkrlZeXSxDMTe+M32a6xXSfnApS1QYJKNXcHrNxo2BKQDG/7D870Ovnqfs29gF+T6rLqPnhiWal6afC7KIL42TY/NWbKyH6gW0xtOg1pL9KfEv5lRjCgSR0vMlzXgo+3K3nZRPQk1EPd8k1AjJtMMmlGBFDV2sckaYbk8lvOO3hRDL5DwXOMYF54aC9ic4fADJjjPCQriDLW2rHibGOTixKIw2LqjWivqB09RxgC8G+CrEjaxxHeV1oJOrAaZ9E+2zZ7GRyqCDXdhC1dFxp8J/UIWEKZbA0n8beC000erbsNBflbevlAl7dAx+HVQAidtahmjWoRMMwqJcJMiJsFoLDUWfladPXcR9rBF9kmlai9T0332KhaZxlVo8Rgux+6JYEE3CkoQRI+L1uRHJceoic95v0MdunoeFScbCuIaJ0BjDEI6xbpdy81dNRXOtBUndxN8r7brkgpzNAoCEbFSQ6qkvvgmpEeOIbRJ7DJixo07hu0mtBvlp9gG3KCM9fj+B+jihSOjxAHxwPoG9fDonA2W9AJwDy970fUzrLQx8KMQ7sVqRe2cnjtlnOC9mBO3mHG397rCbYDWXGzERJnbmJIeEvvl+uIYDxkRsSfpcF6pLUDiqyoo8gC0zxQJXli3JeTJWO6TEZKi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: todo-api-secret
      namespace: todo-api-prod

