apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-api-secret
  namespace: todo-api-prod
spec:
  encryptedData:
    API_KEY: AgBFcn8pW/aB65z8b0McyL0drD1HAFYa2SWQMgr+opPH/RxlXCvmyfDQVEP/au54a+yX/u8I+9NHkWVhFdPxp4+g9DFsrc65pVO1sRIxri4qWzPysHZOruJ5ppJvvA4ODyu1AVmBA9k9gswPal0jJQw0Wvox4FGIvCuhqjeaNatvQ1EVd0FqT+NfvBhVNA3EJbkDOIVvfnNfGpy0QEU6IepHRmqC6StGWily1/b2FGlDk0WRKaOjzzZ+7JvGPXXfIyZJLaFC+RrUly4FVBi17/ufJ5Fq+uvxulBxCYp4uZiUfvKvT03HD4m46/BRp9IjgyrBAWdH+YKFiAYGaDirQS7D1hK9KgsFEh8dMHXoVEw6IaqGHvNISP/x+vt4a+kX+FPY5v0tMInH9nEzdXx8MN8HOMfZEqFXHz2a2jtQhmgW+vjqynF9PQMj+AjsL/uHpyLpQRksvLI0SogjPvzQsZ8iLYA78AywkfQxTCYa/uXtyjPpLF7mFBXAfXfReUqCOJYmeHyHXryCyzZZbo5SCOjYhIO0qNFCfpYueN7bNLIcMEVzOwyB4E1ZFOLD3IaqUiwS9Bi9P45tnRYAsr9XpdklDifkninkQj4BB1bJR0vyV5x8WmZmTZIYwjRkJDg2VTXC0CRWM9iV01RYhcVjabZalzc9ScrltopgMvOFxjCx4Jl5hAZEUlrTJc8qjjts9lliMvxzPKnp7CIR7A==
    DB_PASSWORD: AgBWcd6Z8Q3DmpO2pBJ3soW5atZEZYIKPy3vbvQcHH9dPnItKMZ221SopcVdxmZ3ciYscwq33CuJ3xe1uSVTflOCudQV5BuTFaeSqdwHSYNrHuTZ1fOqvTBA0E3FYYsm25dbA/unUzCqh9dNnBZCgojpXU3C0pSKBfDMEj4zFWrnci8LOStpUw1yBaPz7+tT7UOivXaxbDfDoj0InqjExuqqMQtca+22eQqHmOi/+Zh58tyzzjA6HdPA1M6jODSxFbgmWGH6qJ0D2YDvRXeM2rsYo+4yFb1SPed62+dhtDn4O0COM5Otq4hZDlnZRJzWaBYsrQYFvcnRGH2AZN3995YpDCn9I9vh5XCM4phjo9GXemh3CaQEnOFEJYPuEF97mJ68o9GkufLZKQklnK1KXu5cNO+NGC5BeQzOttYJPaZKa1zqOcCw+hIYdpQP0Uda6sCIyv/jYp5/dD7ewyO2JUtVjPO4NR8X50RCCzTfS4K4Ywaqx4u/Ykheddv2NkhN9i+QZe9tLTiYgLKNLewrbQQQgX/Ne9NJ1/+8o8f6tC7HDMlVJcbdA1bwk2EYzk/SOCBVkMP5vCjiZ2RBTDir3VwCGUy5Ys8CB4dWc9ijDfqsvbWolu1JQiyS8pf3RTwUJBQ2/O+rmiz1SPCmol1mk1vuRawhsWyjz3rAU/BOrNbibqfncyg+tyog0QfWSXn2RCs9bFqakABKVGpz1fQUV7E=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: todo-api-secret
      namespace: todo-api-prod

