name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update image tag
        run: |
          echo "Updated: $(date)" >> apps/todo-api/base/deployment.yaml

      - name: Commit & Push
        run: |
          git config user.email "jeanddjl@gmail.com"
          git config user.name "cronosjl"
          git add apps/todo-api/
          git commit -m "ci: update image [skip ci]" || true
          git push https://cronosjl:${{ secrets.CI_TOKEN }}@github.com/cronosjl/argocd.git main
